### ISSUE TITLE
権限設定

### ISSUE THREAD

**Issue by tosseto** [furuhashilab/sotsuron2018#87]
Mariko Nagano : https://goo.gl/v6AeST

のGoogleDocsの権限設定がcloseになっている。

**Comment by mapconcierge** [comment]
ありがとうございます！
権限設定切り替えました！！
https://docs.google.com/document/d/1sW_ret9VDVPIuZ9wgicpN6_0cnYjpYelB92jUyjGXYo/edit?usp=sharing
